// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_D469LU8vuvl2wQ7uonz0NEsHooDDZ8Q',
    appId: '1:542560367660:web:847536024d8a37efab8d89',
    messagingSenderId: '542560367660',
    projectId: 'not-atlas',
    authDomain: 'not-atlas.firebaseapp.com',
    databaseURL: 'https://not-atlas-default-rtdb.firebaseio.com',
    storageBucket: 'not-atlas.appspot.com',
    measurementId: 'G-X5ZE7NY50V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnKoBuEJc-irFXKlC_vxjl49SD7VrqY0c',
    appId: '1:542560367660:android:5c816b7bbb457255ab8d89',
    messagingSenderId: '542560367660',
    projectId: 'not-atlas',
    databaseURL: 'https://not-atlas-default-rtdb.firebaseio.com',
    storageBucket: 'not-atlas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGdzKTu6dwwftc_C3pvAVfC1TwbHINKp8',
    appId: '1:542560367660:ios:fd8e224f8a217d11ab8d89',
    messagingSenderId: '542560367660',
    projectId: 'not-atlas',
    databaseURL: 'https://not-atlas-default-rtdb.firebaseio.com',
    storageBucket: 'not-atlas.appspot.com',
    iosClientId: '542560367660-8rpil71ttefi3u5sigpkc34menidq5d7.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGdzKTu6dwwftc_C3pvAVfC1TwbHINKp8',
    appId: '1:542560367660:ios:fd8e224f8a217d11ab8d89',
    messagingSenderId: '542560367660',
    projectId: 'not-atlas',
    databaseURL: 'https://not-atlas-default-rtdb.firebaseio.com',
    storageBucket: 'not-atlas.appspot.com',
    iosClientId: '542560367660-8rpil71ttefi3u5sigpkc34menidq5d7.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
